name: GeoCLEWs
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charset-normalizer=2.0.4
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=39.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - descartes=1.1.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fiona=1.8.22
  - flit-core=3.6.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.0.2
  - geojson=2.5.0
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.7.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=68.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - kealib=1.4.14
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lerc=3.0
  - libclang=11.1.0
  - libcurl=7.88.1
  - libdeflate=1.17
  - libgdal=3.0.2
  - libiconv=1.16
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - lxml=4.9.1
  - lz4-c=1.9.4
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=2.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.2.4
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pickleshare=0.7.5
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - plotly=4.12.0
  - plotly_express=0.4.1
  - pooch=1.7.0
  - proj=6.2.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=2.6.1.post1
  - pyqt=5.12.3
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.8
  - pytz=2022.7
  - pywin32=305
  - pywinpty=2.0.10
  - pyzmq=23.2.0
  - qt=5.12.9
  - rasterio=1.2.10
  - rasterstats=0.14.0
  - requests=2.28.1
  - retrying=1.3.3
  - rtree=1.0.1
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=67.6.0
  - shapely=1.7.1
  - simplejson=3.18.3
  - six=1.16.0
  - sniffio=1.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - terminado=0.17.1
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - ucrt=10.0.22621.0
  - urllib3=1.26.14
  - vc=14.3
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.4
  - xz=5.2.10
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
