# Scenario Name
scenario: "Sample"

# Country Name
country: "Kenya"

# Choose your preferred RCP (Representative Concentration Pathway) from the available options: RCP2.6, RCP4.5, RCP6.0, RCP8.5.
rcp: "RCP4.5"

# Admin region level
# 0 for national processing, admin level 0.
# 1 for processing at admin level 1.
admin_level: 1

# Aggregating regions
# If you are processing at admin level 1 and there are more than 7 regions, it is advised to group regions to speed up computational processing.
# "False" indicates no aggregation, "True" performs aggregation.
# Set to True to aggregate into groups.
aggregate: False

# Number of regions to be grouped into one group
region_per_group: 10

# In the case of aggregation, there is an option to extract a specific region and avoid aggregation
# It is required to input the first 3 letters of the specific region e.g. "TAI" refers to Taita Taveta county in Kenya.
#extract: False
#ext_region: "TAI"

# Coordinate and projection systems
# More info: http://epsg.io/
crs_WGS84: CRS("EPSG:4326")
crs_proj: CRS("EPSG:21037")

Full_name = "Kenya"             # Specify the full name of the country you wish to analyze (e.g. Kenya).

RCP = "RCP4.5"                  # Choose your preferred RCP (Representative Concentration Pathway) from the available options: RCP2.6, RCP4.5, RCP6.0, RCP8.5.


admin_level = 1                 # 0 for national processing, admin level 0.
                                # 1 for processing at admin level 1.

#Aggregating regions    
aggregate = False               # If you are processing at admin level 1 and there are more than 7 regions, it is advised to group regions to speed up computational processing.                            
                                # "False" indicates no aggregation, "True" performs aggregation. 
                                # Set to True to aggregate into groups.

region_per_group = 10           # Number of regions to be grouped into one group.
Extract = False                 # In the case of aggregation, there is an option to extract a specific region and avoid aggregation. 
Ext_region = "TAI"              # It is required to input the first 3 letters of the specific region e.g. "TAI" refers to Taita Taveta county in Kenya.
                                


## Coordinate and projection systems
crs_WGS84 = CRS("EPSG:4326")    # For analysis, the original WGS84 coordinate system is used. 
crs_proj = CRS("EPSG:21037")