# Scenario Name
scenario: "Guyana"

# Country Code (Three letters)
geographic_scope: "Guyana"

# Choose your preferred RCP (Representative Concentration Pathway) from the available options: RCP2.6, RCP4.5, RCP6.0, RCP8.5.
rcp: "RCP4.5"

# Admin region level
# 0 for national processing, admin level 0.
# 1 for processing at admin level 1.
admin_level: 0

# Aggregating regions
# If you are processing at admin level 1 and there are more than 7 regions, it is advised to group regions to speed up computational processing.
# "False" indicates no aggregation, "True" performs aggregation.
# Set to True to aggregate into groups.
aggregate: False

aggregate_region: []
# Number of regions to be grouped into one group
region_per_group: 10

# In the case of aggregation, there is an option to extract a specific region and avoid aggregation
# It is required to shapefile the first 3 letters of the specific region e.g. "TAI" refers to Taita Taveta county in Kenya.
#extract: False
#ext_region: "TAI"

# Coordinate and projection systems
# More info: http://epsg.io/
crs_WGS84: "EPSG:4326"
crs_proj: "EPSG:24821"

number_of_clusters: {

    'GUY': 4
}