GLOBAL_RASTER_PATH = "./Data/interim_output/global_raster_input"
CROPPED_RASTER_PATH = "./Data/interim_output/cropped_raster_input"
INPUT_DATA_PATH = "./Data/input"
OUTPUT_DATA_PATH = "./Data/output"
INTERIM_DATA_PATH = "./Data/interim_output"
USER_INPUTS_PATH = "./user_input"
SHAPEFILE_PATH = "./user_input/shapefile"
